<a href="https://colab.research.google.com/github/Byeon-MJ/DL_Practice_Repo/blob/main/NLP_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 딥러닝을 이용한 자연어 처리

## 단어 토큰화 하기

In [1]:
from keras.preprocessing.text import text_to_word_sequence

In [2]:
# 전처리 텍스트
text = '해보지 않으면 해낼 수 없다.'

In [3]:
# 텍스트 토큰화
result = text_to_word_sequence(text)
print('원문:', text)
print("토큰화:", result)

원문: 해보지 않으면 해낼 수 없다.
토큰화: ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
# Tokenizer() 호출
from keras.preprocessing.text import Tokenizer

In [5]:
# 전처리 문장
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.']

In [6]:
# 토큰화 함수를 이용해 전처리
token = Tokenizer()
token.fit_on_texts(docs)

In [7]:
# 단어의 빈도수 계산 결과
print('단어 카운트 :', token.word_counts)

단어 카운트 : OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [8]:
print('문장 카운트:', token.document_count)
print('각 단어가 몇 개의 문장에 포함되어 있는가:', token.word_docs)
print('각 단어에 매겨진 인덱스 값:', token.word_index)

문장 카운트: 3
각 단어가 몇 개의 문장에 포함되어 있는가: defaultdict(<class 'int'>, {'단어를': 1, '각': 1, '토큰화': 3, '먼저': 1, '합니다': 1, '나누어': 1, '텍스트의': 2, '딥러닝에서': 2, '해야': 1, '단어로': 1, '인식됩니다': 1, '수': 1, '결과는': 1, '있습니다': 1, '한': 1, '사용할': 1})
각 단어에 매겨진 인덱스 값: {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


## 영화 리뷰 긍정,부정 예측하기

In [10]:
import numpy as np
import tensorflow as tf
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, Embedding

In [16]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다', '한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']
# Label 지정
labels = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [12]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [14]:
# 패딩. 서로 다른 길이의 데이터를 맞춤
x = token.texts_to_sequences(docs)
padded_x = pad_sequences(x, 4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [15]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index)+1

In [17]:
# 모델 생성, 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, labels, epochs=20)

Epoch 1/20
1/1 [==============================] - 3s 3s/step - loss: 0.6940 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6918 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6895 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6872 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6850 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6827 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6804 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6782 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6759 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6736 - accuracy: 0.9000
Epoch 11/20
1/1 [======================

In [19]:
print(f'Accuracy : {model.evaluate(padded_x, labels)[1]}')

1/1 [==============================] - 0s 21ms/step - loss: 0.6481 - accuracy: 1.0000
Accuracy : 1.0
